NoMenu/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/', include('bulk_import.urls')),
    path('', include('pages.urls')),
    path('account/', include('users.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('account/', include('allauth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.handler404'
handler500 = 'pages.views.handler500'

pages/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='index'),
    path('sendcontact/', views.send_contact_form, name='send-contact-form'),
    path('privacypolicy/', views.privacy_policy_view, name='privacy-policy'),
    path('terms/', views.terms_view, name='terms')
]

restaurant/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('getorder/', views.get_order_items, name='getorder'),
    path('<str:pk>/favorites/', views.get_favorites_view, name='favorites'),
    path('<str:pk>/addfavorite/', views.add_favorites_view, name='add-favorites'),
    path('<str:pk>/order/', views.order_view, name='order'),
    #path('<str:pk>/checkout/order', views.inrestaurant_checkout_view, name='restaurant-checkout'),
    #path('<str:pk>/order/removeitem', views.remove_order_item, name='remove-order-item'),
    #path('<str:pk>/checkout/carryout', views.carryout_checkout_view, name='carryout'),
    path('<str:pk>/', views.restaurant_view, name='menu'),
    path('<str:pk>/order/changequantity', views.modify_item_quantity, name='modify-item-quantity'),
    path('<str:pk>/<slug:id>/', views.category_view, name='category'),
    path('<str:pk>/<slug:cat_id>/<int:item_id>', views.item_view, name='item')
]

restaurant/forms.py
from django import forms
from .models import Order


class BugReportForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea(), required=True, label='message')
    browser_data = forms.CharField(widget=forms.HiddenInput(), required=False, label='browser_data')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['message'].widget.attrs.update({
            'placeholder': 'Provide info about the issue and steps to reproduce.',
            'class': 'form-control',
        })


class RestaurantOrderForm(forms.ModelForm):
    name = forms.CharField(required=True)
    table_number = forms.IntegerField(required=True)

    class Meta:
        model = Order
        fields = ['name', 'table_number']

restaurant/views.py
from typing import List
from urllib.parse import unquote
import json, os, random

from django.contrib import messages
from django.core.mail import BadHeaderError, EmailMessage
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.urls import reverse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Restaurant, Category, RestaurantHours, Order, OrderItem, Menu, Favorite
from .forms import BugReportForm, RestaurantOrderForm
from django.utils.crypto import get_random_string

from django.conf import settings

import boto3

# Create your views here.

# def random_category():
#     session = boto3.session.Session(
#         aws_access_key_id=settings.AWS_ACCESS_KEY_ID,
#         aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY,
#     )
    
#     s3 = session.resource('s3')
#     my_bucket = s3.Bucket('nomenu-prod')

#     arr = []

#     for i in my_bucket.objects.filter(Delimiter='/', Prefix='static/images/'):
#         arr.append(i.key)
        
    
#     random_img = random.choice(arr)
#     a, b, c = random_img.split('/')
#     new_img = "{}/{}".format(b, c)

#     return new_img
    
    

def restaurant_view(request, pk):
    obj: Restaurant = get_object_or_404(Restaurant, cust_pk=pk)

    device_id: str = request.COOKIES.get('device')
    try:
        order_obj: Order = Order.objects.get(
            device=device_id,
            restaurant=obj,
        )
    except Order.DoesNotExist:
        order_obj: Order = Order.objects.create(
            device=device_id,
            restaurant=obj,
        )
    order_has_items: bool = len(OrderItem.objects.filter(order=order_obj)) > 0

    hours = RestaurantHours.objects.get(restaurant=obj)

    menu = Menu.objects.filter(owner=pk)
    category = Category.objects.filter(restaurant=pk).order_by('position')

    fav_items: Favorite = Favorite.objects.filter(restaurant=pk, device=device_id)
    fav: Favorite = [i.item.id for i in fav_items]

    bug_report_form: BugReportForm
    if request.method == 'GET':
        bug_report_form = BugReportForm()
    else:
        bug_report_form = BugReportForm(request.POST)
        if bug_report_form.is_valid():
            # message = "Name: " + name + "\nemail: " + from_email + " \n \n" + form.cleaned_data['message']
            message: str = "Restaurant: {} (ID {})\n \n".format(obj.name, str(obj.cust_pk))
            message += bug_report_form.cleaned_data['message']
            message += "\n\nAttached is a copy of the user's browser data."
            subject: str = "Bug report for restaurant " + obj.name
            try:
                mail: EmailMessage = EmailMessage(subject, message, 'contact@nomenu.io', ['contact@nomenu.io'])
                mail.attach('browser_data.txt', bug_report_form.cleaned_data['browser_data'], 'text/plain')
                mail.send()

                bug_report_form = BugReportForm()
                messages.success(request, "Bug report sent successfully.")
            except BadHeaderError:
                messages.error(request, "Could not send bug report.")

    context = {
        'bug_report_form': bug_report_form,
        'obj': obj,
        'menu': menu,
        'hours': hours,
        'categories': category,
        'order_has_items': order_has_items,
        'fav_items': fav
    }
    return render(request, 'restaurant/menu.html', context)


def category_view(request, pk, id):
    device: str = request.COOKIES.get('device')
    obj = get_object_or_404(Restaurant, cust_pk=pk)

    hours = RestaurantHours.objects.get(restaurant=obj)
    

    category = get_object_or_404(Category, restaurant=pk, slug=id)

    menu_items: Menu = Menu.objects.filter(owner=pk, category__slug=id).order_by('-image', '-image_url', 'title' )
    fav_items: Favorite = Favorite.objects.filter(restaurant=pk, device=device)

    fav: Favorite = [i.item.id for i in fav_items]

    context = {
        'obj': obj,
        'category_page': 'active',
        'category': category,
        'menu_items': menu_items,
        'fav_items': fav,
        'hours': hours
    }
    return render(request, 'restaurant/category.html', context)


def item_view(request, pk, cat_id, item_id):
    restaurant = get_object_or_404(Restaurant, cust_pk=pk)
    category = Category.objects.filter(restaurant=pk, cat_name=cat_id)
    obj = get_object_or_404(Menu, owner=restaurant, id=item_id)

    hours = RestaurantHours.objects.get(restaurant=restaurant)

    device_id: str = request.COOKIES.get('device')

    if request.method == "POST":
        
        try:
            order_obj: Order = Order.objects.get(
                device=device_id,
                restaurant=restaurant,
            )
        except Order.DoesNotExist:
            order_obj: Order = Order.objects.create(
                device=device_id,
                restaurant=restaurant,
            )

        order_item: OrderItem = OrderItem.objects.create(
            order=order_obj,
            item=obj,
            quantity=float(request.POST['quantity']),
            special_instructions=str(request.POST.get('special-instructions'))
        )

        #return redirect('order', pk=restaurant.cust_pk)
    
    fav_items: Favorite = Favorite.objects.filter(restaurant=pk, device=device_id)
    fav: Favorite = [i.item.id for i in fav_items]

    context = {
        'obj': obj,
        'category': category,
        'restaurant': restaurant,
        'fav_items': fav,
        'hours': hours
    }
    return render(request, 'restaurant/item.html', context)


def order_view(request, pk):
    restaurant = get_object_or_404(Restaurant, cust_pk=pk)
    device_id: str = request.COOKIES.get('device')
    try:
        order_obj: Order = Order.objects.get(
            device=device_id,
            restaurant=restaurant,
        )
    except Order.DoesNotExist:
        order_obj: Order = Order.objects.create(
            device=device_id,
            restaurant=restaurant,
        )

    context = {
        'restaurant': restaurant,
        'order_total': order_obj.order_total,
        'order_items': OrderItem.objects.filter(
            order=order_obj,
        ),
    }
    return render(request, 'restaurant/order.html', context)

def remove_order_item(request, pk):
    restaurant = get_object_or_404(Restaurant, cust_pk=pk)
    device_id: str = request.COOKIES.get('device')
    try:
        order_obj: Order = Order.objects.get(
            device=device_id,
            restaurant=restaurant,
        )
        
    except Order.DoesNotExist:
        order_obj: Order = Order.objects.create(
            device=device_id,
            restaurant=restaurant,
        )

    if request.is_ajax():
        item_name: str = request.GET.get('item_name', '')
        
        order_items: OrderItem = OrderItem.objects.filter(id=item_name)

        try:
            item: Menu = [i.id for i in order_items]
            
        except IndexError:
            raise Http404("Item {} not found".format(item_name))
        
        order_items \
            .filter(id=item[0]) \
            .delete()
        return HttpResponse("")
    else:
        return HttpResponse("Nothing to see here.")

def modify_item_quantity(request, pk):
    restaurant = get_object_or_404(Restaurant, cust_pk=pk)
    device_id: str = request.COOKIES.get('device')
    try:
        order_obj: Order = Order.objects.get(
            device=device_id,
            restaurant=restaurant,
        )
    except Order.DoesNotExist:
        order_obj: Order = Order.objects.create(
            device=device_id,
            restaurant=restaurant,
        )

    if request.is_ajax():
        item_name: str = request.GET.get('item_name', '')
        
        new_quantity: int = int(request.GET.get('new_quantity', ''))
        order_items: List[OrderItem] = OrderItem.objects.filter(order=order_obj)

        try:
            item: Menu = [i.item for i in order_items if i.item.title == item_name][0]
        except IndexError:
            raise Http404("Item {} not found".format(item_name))

        order_item: OrderItem = order_items.get(item=item)
        order_item.quantity = new_quantity
        order_item.save()

        return JsonResponse({"newPrice": order_item.total_price})
    else:
        return HttpResponse("Nothing to see here.")

def get_order_items(request):
    response_data = {}

    device = request.COOKIES.get('device')
    cookies = request.COOKIES['nomenu-order']
    order = json.loads(unquote(cookies)) if cookies else []

    for i in order:
        print("item id: ", i['id'])
        print("quantity: ", i['quantity'])


    return JsonResponse(response_data)

def inrestaurant_checkout_view(request, pk):
    restaurant = get_object_or_404(Restaurant, cust_pk=pk)

    device_id = request.COOKIES.get('device')
    name = request.POST.get('name')
    table_number = request.POST.get('table_number')

    try:
        order_obj: Order = Order.objects.filter(
            device=device_id,
            restaurant=restaurant,
        )
    except Order.DoesNotExist:
        order_obj: Order = Order.objects.create(
            device=device_id,
            restaurant=restaurant,
        )
    
    order_form = RestaurantOrderForm()

    if request.method == 'POST':
        order_form = RestaurantOrderForm(request.POST)
        if order_form.is_valid():
            order_obj.update(name=name, table_number=table_number, order_status="ORDERED")
            response = HttpResponseRedirect(reverse('menu', args=(pk,)))
            response.delete_cookie('device')

            return response

    context = {
        'order_form': order_form,
        'restaurant': restaurant
    }

    return render(request, 'restaurant/in_restaurant_checkout.html', context)

def carryout_checkout_view(request, pk):
    context = {}

    return render(request, 'restaurant/carryout_checkout.html', context)


def get_favorites_view(request, pk):

templates/restaurant/base.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-172927976-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-172927976-1');
    </script>

    <title>{% block title %}{{ obj.name }}{% endblock %} - NoMenu</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'restaurant/main.css' %}" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;1,400;1,700&display=swap" rel="stylesheet">
    <link href="{% static 'css/fontawesome-all.min.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    <script type="text/javascript">
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }


        function uuidv4() {
            return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c){
                var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                return v.toString(16);
            });
        }

        let device = getCookie('device');
        if (device == null || device == undefined) {
            device = uuidv4();
        }
        
        document.cookie = 'device=' + device + ";SameSite=Lax;secure=True;domain=;path=/;max-age=" + 30*24*60*60;
    </script>

    {% block extra_scripts %}{% endblock %}
    <link href="https://fonts.googleapis.com/css2?family=Archivo+Narrow:wght@400;500;600&display=swap" rel="stylesheet"> 
    <style>
        .info-button {
            width: 50px;
            height: 50px;
            justify-content: center;
            text-align: center;
            position: absolute;
            top: 20px;
            right: 30px;
            background-color: #FEFEFE;
            padding: 10px;
            border-radius: 50%;
            font-size: 20px;
            box-shadow: 2px 2px 10px #333333;
            z-index: 1000;
        }

        .order-overlay {
            position: absolute;
            background: rgba(0, 0, 0, 0) linear-gradient(rgba(255, 255, 255, 0) 2.5%, rgba(255, 255, 255, 0.92) 55.35%) repeat scroll 0% 0%;
            bottom: 0px;
            top: 0px;
            left: 0px;
            right: 0px;
            z-index: -1;
        }

        .order-button {
            display: flex;
            padding: 13px;
            background-color: #293241;
            box-shadow: rgba(0, 0, 0, 0.1) 0px 0px 8px, rgba(0, 0, 0, 0.04) 0px 4px 4px;
            color: #ffffff;
            align-items: center;
            text-align: center;
            justify-content: center;
            font-family: 'Archivo Narrow';
            border-radius: 4px;
        }
        .order-button-container {
            padding: 12px;
            position: fixed;
            bottom: 0px;
            z-index: 100;
            left: 0px;
            right: 0px;
        }

        .topbar {
            background: #F9F9F9;
            height: 45px;
            box-shadow: 0 2px 4px -1px rgba(0,0,0,0.25);
            overflow: hidden;
        }
        .topbar a {
            float: right;
            text-align: center;
            text-decoration: none;
            padding: 11px;
        }

        .favorite-item {
            color:rgb(224, 28, 28);
        }
        .favorite-item input {
            display: none;
        }
        .favorite-item input ~ span {
            cursor: pointer;
        }
        .favorite-item input ~ .checked {
            display: none;
        }
        .favorite-item input:checked ~ .checked {
            display: inline-block;
        }
        .favorite-item input:checked ~ .unchecked {
            display: none;
        }

        .favorite-overlay {
            position: absolute;
            background: rgba(0, 0, 0, 0) linear-gradient(rgba(255, 255, 255, 0) 2.5%, rgba(255, 255, 255, 0.92) 55.35%) repeat scroll 0% 0%;
            bottom: 0px;
            top: 0px;
            left: 0px;
            right: 0px;
            z-index: -1;
        }

        .favorite-button {
            display: flex;
            padding: 13px;
            background-color: #293241;
            box-shadow: rgba(0, 0, 0, 0.1) 0px 0px 8px, rgba(0, 0, 0, 0.04) 0px 4px 4px;
            color: #ffffff;
            align-items: center;
            text-align: center;
            justify-content: center;
            font-family: 'Archivo Narrow';
            border-radius: 4px;
        }
        .favorite-button-container {
            display: none;
            padding: 12px;
            position: fixed;
            bottom: 0px;
            z-index: 100;
            left: 0px;
            right: 0px;
        }
    </style>
</head>
<body>
    {% block top-bar %}
    {% endblock top-bar %}

    {% block cart-button %} {% endblock cart-button %}
    {% block content %}

    {% endblock %}

    {% block modal-content %}
    {% endblock modal-content %}
</body>
</html>

templates/restaurant/carryout_checkout.html
{% extends 'restaurant/base.html' %}
{% load static %}
{% load thumbnail %}

{% block content %}
<div class="container">
    <div class="row">
        <form>
            
        </form>
    </div>
</div>
{% endblock %}

templates/restaurant/category.html
{% extends 'restaurant/base.html' %}
{% load static %}
{% load thumbnail %}

{% block top-bar %} 

{% endblock %}

{% block cart-button %}
<div class="topbar">
    <div class="container">
      <a href="#" data-toggle="modal" data-target="#info-modal"><i style="font-size: 20px;" class="fas fa-info-circle"></i></a>
    </div>
</div>
<!--
<div class="order-button-container">
    <div class="order-overlay"></div>
    <a href="{% url 'order' obj.cust_pk %}" class="order-button">View Order</a>
</div>
-->

<div class="favorite-button-container">
    <div class="favorite-overlay"></div>
    <a href="{% url 'favorites' obj.cust_pk %}" class="favorite-button">View Favorites</a>
</div>

{% endblock cart-button %}

{% block extra_scripts %} 
    <script>
        var favoritesURL = "{% url 'add-favorites' pk=obj.cust_pk %}";
        {% if fav_items %}
            $(document).ready(function(){
                $('.favorite-button-container').show();
            });
        {% endif %}
    </script>
    <script src="{% static 'restaurant/favorites.js' %}"></script>

{% endblock %}

{% block content %}
{% if obj.is_live == True %}

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                
                
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <a href=".." class="pr-3"><i class="fas fa-arrow-left mt-3"></i></a>
                <h4 class="text-center" style="font-family: 'Archivo Narrow';">{{ category.cat_name|title }}</h4>
                {% if category.description %}
                <h6 class="text-center">{{ category.description }}</h6>
                {% endif %}
                <hr>
                
            </div>
        </div>

        <div class="row" style="margin-bottom: 90px;">
            
            
            {% for menu_item in menu_items %}
                {% if menu_item.is_shown == True %}

                <div class="col-lg-4 col-md-6 col-sm-6 mb-4">
                    <a class="card-link" href="{% url 'item' obj.pk category.slug menu_item.id %}">
                        <div class="new-card">
                            {% if menu_item.image_url %}
                            <div class="thumb" width="350" height="240" style="background: url('{{ menu_item.image_url }}') no-repeat center;background-size: cover;"></div>
                            {% elif menu_item.image %}
                            <div class="thumb" style="background: url('{% thumbnail menu_item.image 350x240 upscale=True crop='smart' %}') no-repeat center;background-size: cover;"></div>
                            {% else %}
                            
                            {% endif %}
                            <div class="infos">
                                <h5 class="title text-center">{{ menu_item.title | title }} </h5>
                    </a>
                                
                                <hr class="new">
                                <p>{{ menu_item.description | truncatewords:10 }}</p>
                                <p style="color: rgb(156, 25, 25);"><small>{% if menu_item.allergens != "" %}Allergens: {{ menu_item.allergens | title }}{% endif %}</small></p>
                                <hr >
                                <div class="mt-2 mb-2">

                                    
                                    <label class="favorite-item">
                                        <input type="checkbox" class="fav-item" name="favorites" data-id="{{ menu_item.id }}" {% if menu_item.id in fav_items %}checked{% endif %}>
                                        <span class="far fa-heart unchecked"></span>
                                        <span class="fas fa-heart checked"></span>
                                    </label>
                                    
                                    {% if menu_item.price %}
                                        <p class="pricing pt-0">{{ menu_item.priceString }}</p>
                                    {% endif %}
                                </div>
                                
                            </div>
                        </div>
                    
                </div>

                {% endif %}
            {% endfor %}

        </div>

    </div>

{% else %}
<div class="container mt-5">
    <div class="text-center">
      <h5>Sorry, this restaurant has not published their menu yet!</h5>
    </div>
  </div>
{% endif %}


{% endblock %}

{% block modal-content %}
{% include 'restaurant/info_modal.html' %}
{% endblock modal-content %}

templates/restaurant/favorites.html
{% extends 'restaurant/base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %}{{ obj.name }}{% endblock %}

{% block extra_scripts %}
<script>
    var favoritesURL = "{% url 'add-favorites' pk=obj.cust_pk %}";
</script>
<script src="{% static 'restaurant/favorites.js' %}"></script>
{% endblock %}

{% block top-bar %} 
<div class="topbar">
    <div class="container">
      <a href="#" data-toggle="modal" data-target="#info-modal"><i style="font-size: 20px;" class="fas fa-info-circle"></i></a>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <br/>
            <a href="javascript:history.go(-1)"><i class="fas fa-arrow-left"></i></a>
            <br/>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h4 class="text-center">My Favorites</h4>
            <hr>
        </div>
    </div>

    {% for fav_item in fav_items %}

        <div class="card mb-2 w-100 fav-card">
            <div class="row no-gutters">

                    
                    <div class="col-auto">
                        <a href="{% url 'item' fav_item.restaurant.pk fav_item.item.category.slug fav_item.item.id %}" style="color:black;text-decoration: none;">
                        {% if fav_item.item.image_url %}
                        <div style="width:100px;height: 100px;background:url('{{ fav_item.item.image_url }}') no-repeat center;background-size: cover;" class="text-center"></div>
                        {% elif fav_item.item.image %}
                        <img src="{% thumbnail fav_item.item.image 100x100 upscale=True crop='smart' %}">
                        {% else %}
                        
                        {% endif %}
                        </a>
                    </div>
                

                <div class="col">
                    <a href="{% url 'item' fav_item.restaurant.pk fav_item.item.category.slug fav_item.item.id %}" style="color:black;text-decoration: none;">
                        <div class="card-block px-2 mt-2">
                            <p class="card-title mb-1 item-name" style="font-weight: bold;">{{ fav_item.item.title | title }}</p>
                            {% if fav_item.item.price %}
                                <p class="mb-0" style="font-size: 12px;">${{ fav_item.item.price }}</p>
                            {% endif %}
                        </div>
                    </a>

                    <a href="" style="position: absolute;bottom: 3px;right: 2px;padding-right:15px;font-size:13px;" class="remove-fav float-right" data-id="{{ fav_item.id }}">Remove</a>
                </div>
            </div>
        </div>
    {% empty %}
    <div class="no-items">
        <p>You haven't added anything yet!</p>
    </div>
    
    {% endfor %}
</div>
{% endblock %}

{% block modal-content %}
{% include 'restaurant/info_modal.html' %}
{% endblock modal-content %}

templates/restaurant/menu.html
{% extends 'restaurant/base.html' %}
{% load static %}

{% block top-bar %} 
<div class="topbar">
  <div class="container">
    <a href="#" data-toggle="modal" data-target="#bug-report-modal"><i style="font-size: 20px;" class="fas fa-bug"></i></a>
    <a href="#" data-toggle="modal" data-target="#info-modal"><i style="font-size: 20px;" class="fas fa-info-circle"></i></a>
  </div>
</div>

{% for message in messages %}
<div class="topbar {{ message.tags }}">
  <div class="container d-flex align-items-center h-100">
    <p class="text-light m-0">{{ message }}</p>
  </div>
</div>
{% endfor %}

<div class="favorite-button-container">
    <div class="favorite-overlay"></div>
    <a href="{% url 'favorites' obj.cust_pk %}" class="favorite-button">View Favorites</a>
</div>
{% endblock %}

{% block extra_scripts %} 
    <script>
        var favoritesURL = "{% url 'add-favorites' pk=obj.cust_pk %}";

        {% if fav_items %}
            $(document).ready(function(){
                $('.favorite-button-container').show();
            });
        {% endif %}
    </script>
    <script src="{% static 'restaurant/favorites.js' %}"></script>

{% endblock %}

{% block cart-button %}
<!--
<div class="order-button-container">
  <div class="order-overlay"></div>
  <a href="{% url 'order' obj.cust_pk %}" class="order-button">View Order</a>
</div>
-->
{% endblock cart-button %}

{% block content %}




<div class="modal fade" id="bug-report-modal" tabindex="-1" role="dialog" aria-labelledby="bug-report-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="bug-report-modal-label">Bug Report</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <i class="fas fa-times"></i>
        </button>
      </div>
      <div class="modal-body">
        <p>Found an issue? The NoMenu team would love to help fix it.</p>
        <form method="post" id="bug-report-form">
					{% csrf_token %}
					{{ bug_report_form.message }}
          <p><small>Note: A copy of your browser metadata will be sent alongside this report. This includes, but is not limited to, your browser version and operating system. Your IP address and other identifying information are not included.</small></p>
          {{ bug_report_form.browser_data }}
          <input class="btn btn-success" type="submit" value="Send">
          <script>
          $('#bug-report-form').on('submit', () => {
            let browserData = "";
            for (var property in window.navigator) {
              browserData += `${property}: ${window.navigator[property]}\n`
            }
            $("#id_browser_data").val(browserData);
          });
          </script>
				</form>
      </div>
    </div>
  </div>
</div>


<div class="container mt-5">
        <div class="text-center">
        
          {% if obj.rest_logo %}
            <img src="{{ obj.rest_logo.url }}"  class="d-inline-block align-top" width="250px">
          {% else %}
            <h2>{{ obj.name }}</h2>
          {% endif %}

      </div>
</div>

{% if obj.is_live == True %}
<div class="product-categories">
    <section class="product-container">
        <div class="product-content">
            <ul class="product-grid">
                <li class="product-wide" style="margin-bottom: 90px;">

                    {% for category in categories %}
                      {% if category.is_shown == True %}
                      <a href="{% url 'category' obj.pk category.slug %}" class="gradient">
                          <div class="category-details">
                              {% if category.cat_img %}
                              <div class="img-container" style="background-image: url(' {{ category.cat_img.url }} ');"></div>
                              {% else %}
                              <div class="img-container" style="background-image: url( '{% static 'images/DINNER.jpg' %}' );"></div>
                              {% endif %}

                              <div class="category-title">{{ category.cat_name|upper }}</div>
                          </div>
                      </a>
                      {% endif %}
                    {% endfor %}

                </li>
            </ul>
        </div>
    </section>
</div>
{% else %}
<div class="container mt-5">
  <div class="text-center">
    <h5>Sorry, this restaurant has not published their menu yet!</h5>
  </div>
</div>

{% endif %}
{% endblock %}

{% block modal-content %}
{% include 'restaurant/info_modal.html' %}
{% endblock modal-content %}