NoMenu/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/', include('bulk_import.urls')),
    path('', include('pages.urls')),
    path('account/', include('users.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('account/', include('allauth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.handler404'
handler500 = 'pages.views.handler500'

dashboard/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('analyticsdata', views.analytics_data, name='analytics-data'),
    path('account/', views.account_view, name='account'),
    path('account/update/', views.account_update_view, name='update-account'),
    #path('manage/', views.create_menu, name='managemenu'),
    path('update/<str:pk>', views.menu_item_update_view, name='update-menu'),
    path('manage/', views.create_category, name='managemenu'),
    path('add/<slug:id>', views.add_by_category_view, name='category-add'),
    path('updatecategory/', views.category_update_view, name='update-category'),
    path('updatecategorysave/<int:pk>', views.save_category_update_view, name='save-category-update'),
    path('deleteitem/<str:pk>', views.menu_item_delete_view, name='delete-menu-item'),
    #path('qrcode/', views.qrcode_view, name='qrcode'),
    path('restaurant/', views.restaurant_info, name='restaurant'),
    path('restaurant/update/', views.restaurant_update_view, name='update-restaurant'),
    path('item/<pk>', views.item_detail, name='item-detail'),
    path('togglemenu/<int:pk>', views.set_menu_hidden_view, name='toggle-menu'),
    path('updateposition/<int:pk>', views.update_position_view, name='update-position'),
    path('deletemenuitem/<int:pk>', views.delete_menu_item, name='delete-menu-item'),
    path('deletecatitem/<int:pk>', views.delete_cat_item, name='delete-cat-item'),
    path('loadmenuitem/', views.load_menu_item, name='load-menu-item'),
    path('updatemenuitem/<int:pk>', views.update_menu_item, name='update-menu-item'),
    path('hidecategory/', views.hide_category_view, name='hide-category'),
    path('fetchorders/', views.fetch_orders_view, name='fetch-orders'),
    path('publishmenu/', views.publish_menu_view, name='publish-menu'),
    path('removeimage/', views.remove_image_view, name='remove-image'),
    path('removemenuimage/', views.remove_menu_item_image, name='remove-menu-image')
]

pages/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='index'),
    path('sendcontact/', views.send_contact_form, name='send-contact-form'),
    path('privacypolicy/', views.privacy_policy_view, name='privacy-policy'),
    path('terms/', views.terms_view, name='terms')
]

restaurant/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('getorder/', views.get_order_items, name='getorder'),
    path('<str:pk>/favorites/', views.get_favorites_view, name='favorites'),
    path('<str:pk>/addfavorite/', views.add_favorites_view, name='add-favorites'),
    path('<str:pk>/order/', views.order_view, name='order'),
    #path('<str:pk>/checkout/order', views.inrestaurant_checkout_view, name='restaurant-checkout'),
    #path('<str:pk>/order/removeitem', views.remove_order_item, name='remove-order-item'),
    #path('<str:pk>/checkout/carryout', views.carryout_checkout_view, name='carryout'),
    path('<str:pk>/', views.restaurant_view, name='menu'),
    path('<str:pk>/order/changequantity', views.modify_item_quantity, name='modify-item-quantity'),
    path('<str:pk>/<slug:id>/', views.category_view, name='category'),
    path('<str:pk>/<slug:cat_id>/<int:item_id>', views.item_view, name='item')
]

restaurant/models.py
import os, random, datetime
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string
from django.conf import settings
from localflavor.us.models import USStateField, USZipCodeField
from django.utils.translation import gettext as _
from django.db.models.signals import pre_save, post_save
from django.utils.html import mark_safe
from django.dispatch import receiver
from NoMenu.utils import unique_slug_generator

# Create your models here.

def user_directory_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    randomstr = ''.join((random.choice(chars)) for x in range(15))

    return 'uploads/{0}/profile/{1}{2}'.format(instance.cust_pk, randomstr, file_extension)

class Restaurant(models.Model):
    cust_pk = models.CharField(max_length=6, primary_key=True, editable=False, unique=True)
    rest_logo = models.ImageField(null=True, blank=True, upload_to=user_directory_path)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=99, blank=True, null=True)
    address1 = models.CharField(max_length=99, blank=True, null=True)
    address2 = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    state = USStateField(blank=True, null=True)
    zipcode = USZipCodeField(blank=False, null=True)
    phone = models.CharField(max_length=20, blank=True)
    is_live = models.BooleanField(default=False)
    is_demo = models.BooleanField(default=False)

    def __str__(self):
        return "%s - (%s: %s)" % (self.name, self.cust_pk, self.owner)

    def get_absolute_url(self):
        return reverse('order', kwargs={'pk': self.cust_pk})

    @property
    def google_maps_url(self):
        def process_segment(s):
            return s.replace(" ", "+").replace(",", "%2C")

        out = "https://www.google.com/maps/search/?api=1&query="
        out += process_segment(self.address1) + "%2C+"
        if self.address2:
            out += process_segment(self.address2) + "%2C+"
        out += process_segment(self.city) + "%2C+"
        out += process_segment(self.state) + "+"
        out += process_segment(self.zipcode)

        return out

    def save(self, *args, **kwargs):
        if not self.cust_pk:
            self.cust_pk = get_random_string(length=6, allowed_chars='0123456789')
        return super(Restaurant, self).save(*args, **kwargs)

        
def cat_directory_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    randomstr = ''.join((random.choice(chars)) for x in range(15))

    return 'uploads/{0}/category/{1}{2}'.format(instance.restaurant.cust_pk, randomstr, file_extension)

class Category(models.Model):
    slug = models.SlugField(max_length=100, null=True)
    position = models.DecimalField(max_digits=3, default=0, decimal_places=0)
    is_shown = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, null=True)
    cat_name = models.CharField(max_length=50, blank=True, null=True)
    cat_img = models.ImageField(null=True, blank=True, upload_to=cat_directory_path)
    description = models.CharField(max_length=256, null=True, blank=True)

    class Meta:
        unique_together = ['restaurant', 'cat_name']
    
    def __str__(self):
        return "%s - (%s: %s)" % (self.cat_name.title(), self.restaurant.cust_pk, self.restaurant.owner)
    
    def save(self, *args, **kwargs):
        self.cat_name = self.cat_name and self.cat_name.lower()

        # set our position to the highest existing position + 1
        categories = Category.objects.filter(restaurant=self.restaurant)
        if len(categories) > 0:
            highest_pos = int(max((c.position for c in categories)))
            self.position = highest_pos + 1

        super(Category, self).save(*args, **kwargs)

def pre_save_receiver(sender, instance, *args, **kwargs): 
    if not instance.slug: 
        instance.slug = unique_slug_generator(instance) 

pre_save.connect(pre_save_receiver, sender = Category) 


def menu_directory_path(instance, filename):
    basefilename, file_extension = os.path.splitext(filename)
    chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'
    randomstr = ''.join((random.choice(chars)) for x in range(15))
    
    return 'uploads/{0}/menu/{1}{2}'.format(instance.owner.pk, randomstr, file_extension)

class Menu(models.Model):
    # default options for "units" field
    # database item : human readable
    UNIT_CHOICES = {
        "EA": "each",
        "OZ": "per ounce",
        "LB": "per pound",
        "OT": "other",
    }

    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL)
    owner = models.ForeignKey(Restaurant, to_field='cust_pk', null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=100)
    price = models.DecimalField(decimal_places=2, max_digits=1000, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(blank=True, upload_to=menu_directory_path)
    image_url = models.CharField(max_length=400, blank=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    is_shown = models.BooleanField(default=True)
    units = models.CharField(
        max_length=2,
        choices=UNIT_CHOICES.items(),
        default="EA"
    )
    custom_unit = models.CharField(max_length=64, blank=True)
    allergens = models.CharField(max_length=128, blank=True)

    def __str__(self):
        return "%s - (%s : %s)" % (self.title.title(), self.owner.cust_pk, self.owner.owner)

    def get_absolute_url(self):
        return reverse('item', kwargs={'pk': self.owner.cust_pk, 'cat_id': self.category.slug, 'item_id': self.pk})

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    @property
    def priceString(self):
        base = "$" + str(self.price)
        if self.units == "EA":
            return base
        base += " "
        if self.units == "OT":
            return base + self.custom_unit
        return base + self.UNIT_CHOICES[self.units]



HOUR_OF_DAY_24 = [(i,i) for i in range(1,25)]
WEEKDAYS = (
    (0, _("Monday")),
    (1, _("Tuesday")),
    (2, _("Wednesday")),
    (3, _("Thursday")),
    (4, _("Friday")),
    (5, _("Saturday")),
    (6, _("Sunday"))
)


class RestaurantHours(models.Model):
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)

    monday = models.BooleanField(default=True)
    monday_hours = models.CharField(max_length=256)
    tuesday = models.BooleanField(default=True)
    tuesday_hours = models.CharField(max_length=256)
    wednesday = models.BooleanField(default=True)
    wednesday_hours = models.CharField(max_length=256)
    thursday = models.BooleanField(default=True)
    thursday_hours = models.CharField(max_length=256)
    friday = models.BooleanField(default=True)
    friday_hours = models.CharField(max_length=256)
    saturday = models.BooleanField(default=True)
    saturday_hours = models.CharField(max_length=256)
    sunday = models.BooleanField(default=True)
    sunday_hours = models.CharField(max_length=256)

    def __str__(self):
        return "%s" % (self.restaurant)

class SpecialDays(models.Model):
    holiday_date = models.DateField()
    closed = models.BooleanField(default=True)
    from_hour = models.PositiveSmallIntegerField(choices=HOUR_OF_DAY_24, null=True, blank=True)
    to_hour = models.PositiveSmallIntegerField(choices=HOUR_OF_DAY_24, null=True, blank=True)


class TableNumber(models.Model):
    table = models.CharField(max_length=10, null=True, blank=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)

class Order(models.Model):
    ORDER_STATUS = (
        ('ORDERED', 'ORDERED'),
        ('CONFIRMED', 'CONFIRMED'),
        ('IN PROGRESS', 'IN PROGRESS'),
        ('READY', 'READY'),
        ('COMPLETE', 'COMPLETE'),
        ('CANCELLED', 'CANCELLED'),
    )

    device = models.CharField(max_length=300, null=True, blank=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.PROTECT)
    table_number = models.CharField(max_length=100, null=True, blank=True)
    order_number = models.CharField(max_length=7, editable=False, unique=True)
    quantity = models.PositiveIntegerField(null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=99, blank=True, null=True)
    address1 = models.CharField(max_length=99, blank=True, null=True)
    address2 = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    state = USStateField(blank=True, null=True)
    zipcode = USZipCodeField(blank=False, null=True)
    phone = models.CharField(max_length=20, blank=True)
    order_status = models.CharField(choices=ORDER_STATUS, max_length=200, null=True, blank=True, default="")
    order_type = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return "%s" % (self.order_number)

    @property
    def get_date(self):
        return self.date_ordered.strftime("%m/%d/%Y %H:%M")

    @property
    def order_total(self):
        return sum(
            ((i.item.price * i.quantity) for i in OrderItem.objects.filter(order=self))
        )
    
    def save(self, *args, **kwargs):
        if not self.order_number:
            self.order_number = get_random_string(length=7, allowed_chars='0123456789')
        #if not self.date_ordered:

dashboard/forms.py
from copy import deepcopy

from django import forms
from django.db.models import Q
from restaurant.models import Category, Restaurant, RestaurantHours, Menu
from django.contrib.auth.models import User

class MenuForm(forms.ModelForm):
    image = forms.ImageField(required=False, label='', widget=forms.FileInput)
    
    class Meta:
        model = Menu
        fields = ('title', 'price', 'units', 'custom_unit', 'description', 'allergens', 'image_url', 'image')
    
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        return super(MenuForm, self).__init__(*args, **kwargs)
        self.fields['image'].label = ''

    def save(self, *args, **kwargs):
        kwargs['commit']=False
        obj = super(MenuForm, self).save(*args, **kwargs)
        if self.request:
            obj.user = self.request.user
        obj.save()
        return obj

class CategoryForm(forms.ModelForm):
    cat_name = forms.CharField(required=False)

    class Meta:
        model = Category
        fields = ('cat_name',)

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.fields['cat_name'].widget.attrs.update({'placeholder': 'Enter a category'})

class CategoryFormUpload(forms.ModelForm):
    cat_name = forms.CharField(required=True)
    cat_img = forms.ImageField(widget=forms.FileInput, required=False)

    class Meta:
        model = Category
        fields = ('cat_name', 'description', 'cat_img')

    def __init__(self, *args, **kwargs):
        super(CategoryFormUpload, self).__init__(*args, **kwargs)
        self.fields['cat_name'].widget.attrs.update({'placeholder': 'Enter a category'})
        self.fields['cat_name'].label = ' Category Name: '
        self.fields['cat_img'].label = ''

    #def clean(self):
    #    cleaned_data = self.cleaned_data
    #    cat_name = cleaned_data['cat_name']

    #    if cat_name and Category.objects.get(cat_name=cat_name):
    #        raise forms.ValidationError("Entry already exists")
    #    return cleaned_data


class RestaurantUpdateForm(forms.ModelForm):
    rest_logo = forms.ImageField(widget=forms.FileInput, required=False)

    class Meta:
        model = Restaurant
        fields = ('name', 'address1', 'address2', 'city', 'state', 'zipcode', 'phone', 'rest_logo')
    
    def __init__(self, *args, **kwargs):
        super(RestaurantUpdateForm, self).__init__(*args, **kwargs)
        self.fields['name'].label = 'Restaurant Name'
        self.fields['address1'].label = 'Address Line 1'
        self.fields['address2'].label = 'Address Line 2'
        self.fields['rest_logo'].label = ''

class RestaurantHoursUpdateForm(forms.ModelForm):
    class Meta:
        model = RestaurantHours
        exclude = ['restaurant']

    def __init__(self, *args, **kwargs):
        self.prev_model = deepcopy(kwargs.get("instance"))
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.required = False

    def save(self):
        new_model = super().save(commit=False)

        new_model.monday_hours = new_model.monday_hours or self.prev_model.monday_hours
        new_model.tuesday_hours = new_model.tuesday_hours or self.prev_model.tuesday_hours
        new_model.wednesday_hours = new_model.wednesday_hours or self.prev_model.wednesday_hours
        new_model.thursday_hours = new_model.thursday_hours or self.prev_model.thursday_hours
        new_model.friday_hours = new_model.friday_hours or self.prev_model.friday_hours
        new_model.saturday_hours = new_model.saturday_hours or self.prev_model.saturday_hours
        new_model.sunday_hours = new_model.sunday_hours or self.prev_model.sunday_hours
        
        new_model.save()

templates/dashboard/account.html
{% extends 'dashboard/base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load thumbnail %}

{% block content %}

            <!-- MAIN CONTENT-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        {% if messages %}
                        {% for message in messages %}
                            {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                            <div class="sufee-alert alert with-close alert-success alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            {% endif %}
                            
                            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                            <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                            {% endif %}

                        {% endfor %}
                        {% endif %}

                        <div class="row">
                            <div class="col-md-12">
                                <div class="overview-wrap">
                                    <h2 class="title-1">Account Overview</h2>
                                </div>
                            </div>
                        </div>
<br>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="card">
                                    <div class="card-header">
                                        <i class="fa fa-user"></i>
                                        <strong class="card-title pl-2">Your Profile</strong>
                                    </div>
                                    <div class="card-body">
                                        <div class="mx-auto d-block">
                                            <img class="rounded-circle mx-auto d-block" src="{% thumbnail request.user.profile_img 200x200 upscale=True crop='smart' %}" />
                                            <h5 class="text-sm-center mt-2 mb-1">{{ request.user.first_name | title }} {{ request.user.last_name | title }}</h5>
                                            <div class="text-sm-center">
                                                <p>{{ request.user.email }}</p>
                                                <p></p>
                                            </div>
                                        </div>
                                        <hr>
                                        <div class="card-text text-sm-center">
                                            <a href="{% url 'update-account' %}">EDIT</a>
                                        </div>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT-->

{% endblock %}

templates/dashboard/account_edit.html
{% extends 'dashboard/base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block content %}

            <!-- MAIN CONTENT-->
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="overview-wrap">
                                    <h2 class="title-1">Account Overview</h2>
                                </div>
                            </div>
                        </div>
<br>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="card">
                                    <div class="card-header">
                                        <i class="fa fa-user"></i>
                                        <strong class="card-title pl-2">Your Profile</strong>
                                    </div>
                                    <div class="card-body">
                                        <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
                                            
                                            {{ form.as_p }}
                                        <input type="submit">
                                        </form>
                                        
                                        <hr>
                                        <div class="card-text text-sm-center">
                                            <p>EDIT</p>
                                        </div>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT-->

{% endblock %}

templates/dashboard/category_update.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          <div class="card">
            <div class="card-header">
              <strong class="card-title">Update Category</strong>
            </div>
            <div class="card-body">

              <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
                {% for field in category_form %}
                <div class="form-group">
                  {% render_field field class="form-control" placeholder=field.label %}
                </div>
                {% endfor %}
                <button class="btn btn-outline-success" type="submit">Save</button>
                
              </form>
              
              

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/dashboard/category_update_modal.html
{% load widget_tweaks %}
<form method="POST" action="{% url 'save-category-update' pk=obj.pk %}" enctype="multipart/form-data">
<div class="modal-body category-modal-body">
    
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label for="field.label">{{field.label}}</label>
            {% render_field field class="form-control" %}
        </div>
        {% endfor %}


    <br>


    <button class="btn btn-secondary btn-sm" id="uploadTriggerCategory">
        <i class="fa fa-picture-o"></i>
        Upload Image
    </button>
    <br>
    <br>
    <div id="category-image-holder">
        {% if obj.cat_img %}
        <p>Current Image:</p>
        <img width="100px" src="{{ obj.cat_img.url }}">
        {% endif %}
    </div>

    </div>

        <div class="modal-footer">
            <button type="button" id="cancelButton" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </form>

templates/dashboard/menu_create_modal.html
{% load widget_tweaks %}


<!-- modal large -->
<div class="modal fade" id="largeModal" tabindex="-1" role="dialog" aria-labelledby="largeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="largeModalLabel">Create a {{ category.cat_name }} item</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group">
                        {% render_field field class="form-control" placeholder=field.label %}
                    </div>
                    {% for error in field.errors %}
                        {{ error}}
                    {% endfor %}
                    
                    {% endfor %}
                    <p>OR</p>
                    <br>
                    
                    <button class="btn btn-secondary btn-sm" id="uploadTrigger">
                        <i class="fa fa-picture-o"></i>
                        Upload Image
                    </button>
                    <br><br>
                    <div id="image-holder"></div>
                    <br>
                    <div id="noImage" style="color:red;font-size: 13px;"></div>
                    
                
            </div>
            <div class="modal-footer">
                <button type="button" id="cancelButton" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="reset" id="formReset" hidden></button>
                <button type="submit" class="btn btn-primary createmenusave">Save</button>
            </form>

            
            </div>
        </div>
    </div>
</div>
<!-- end modal large -->

templates/dashboard/nav_desktop.html
{% load static %}
<!-- HEADER DESKTOP-->
<header class="header-desktop">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="header-wrap">

                <div class="header-button">
                    <div class="account-wrap">
                        <div class="account-item clearfix js-item-menu">
                            <div class="content">
                                <a class="js-acc-btn" href="#">{{ request.user.first_name | title }} {{ request.user.last_name | title }}</a>
                            </div>
                            <div class="account-dropdown js-dropdown">
                                <div class="account-dropdown__body">
                                    <div class="account-dropdown__item">
                                        <a href="{% url 'account' %}">
                                            <i class="zmdi zmdi-account"></i>Account</a>
                                    </div>
                                    <div class="account-dropdown__item">
                                        <a href="#">
                                            <i class="zmdi zmdi-settings"></i>Settings</a>
                                    </div>
                                </div>
                                <div class="account-dropdown__footer">
                                    <a href="{% url 'account_logout' %}">
                                        <i class="zmdi zmdi-power"></i>Logout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- HEADER DESKTOP-->

templates/dashboard/update_menu_item.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          <div class="card">
            <div class="card-header">
              <strong class="card-title">Update Menu</strong>
            </div>
            <div class="card-body">

              <form method="POST" enctype="multipart/form-data" action="">{% csrf_token %}
                {% for field in menu_form %}
                <div class="form-group">
                  {% render_field field class="form-control" placeholder=field.label %}
                </div>
                {% endfor %}


                
                <div class="form-group">
                  <select id="id_category" class="form-control" name="category" placeholder="Category" required="">
                    {% for cat in current_category %}
                      <option value="{{ cat.category }}" selected="{{ cat.category }}" >{{ cat.category }}</option>
                    {% endfor %}
                      
                      {% for cat in category %}
                          <option value='{{ cat.cat_name }}'>{{ cat.cat_name }}</option>
                      {% endfor %}
                      
                  </select>
                </div>
                <button class="btn btn-outline-success" type="submit">Save</button>
                
              </form>
              
              

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}